# Generated by Django 3.2.4 on 2021-07-01 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bidType', models.CharField(choices=[('CPC', 'CPC'), ('VCPM', 'VCPM')], max_length=100)),
                ('cpc', models.FloatField()),
                ('budget', models.FloatField()),
                ('pacing', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], max_length=100)),
                ('photoFileName', models.CharField(max_length=100)),
                ('scheduling', models.JSONField()),
                ('targeting', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='campaigns.campaign')),
            ],
        ),
    ]
